### PR TITLE
imx7ulp: fix suspending to vlls instead of vlps

### PR DESCRIPTION
**Pull request by vanmaegima**
Revert "[fio extras] imx7ulp poweroff state"
This reverts commit d6438781e1e98dc4d246a9302b2b7035112745c0.

Use the standard pm framework for imx7ulp.

### CODE REVIEW

**Review by MrCry0 — COMMENTED** [review]
Could you add a short problem description this reverting is fixing?

**Comment by vanmaegima** [comment]
> Could you add a short problem description this reverting is fixing?

@MrCry0 done

**Review by MrCry0 — APPROVED** [review]
LGTM

**Review by Tim-Anderson — APPROVED** [review]
LGTM

**Review by mike-scott — APPROVED** [review]
Nice to drop a commit here.

**Review by ricardosalveti — APPROVED** [review]
LGTM

**Pull request merged**
